[package]
name = "event-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures-util = "0.3.21"
pretty_env_logger = "0.4.0"
log = "0.4.16"
tokio-stream = "0.1.8"
ulid = "0.5.0"
